/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/SubwayMap` | `/MM/SubwayMap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/loading` | `/MM/loading`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/location` | `/MM/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/main` | `/MM/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/searchResult` | `/MM/searchResult`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/searchScreen` | `/MM/searchScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/favorite` | `/menu/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/login` | `/menu/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/settings` | `/menu/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/terms` | `/menu/terms`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MM/SubwayMap` | `/MM/SubwayMap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MM/loading` | `/MM/loading`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MM/location` | `/MM/location`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MM/main` | `/MM/main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MM/searchResult` | `/MM/searchResult`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MM/searchScreen` | `/MM/searchScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu/favorite` | `/menu/favorite`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu/login` | `/menu/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu/settings` | `/menu/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu/terms` | `/menu/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MM/SubwayMap${`?${string}` | `#${string}` | ''}` | `/MM/SubwayMap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MM/loading${`?${string}` | `#${string}` | ''}` | `/MM/loading${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MM/location${`?${string}` | `#${string}` | ''}` | `/MM/location${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MM/main${`?${string}` | `#${string}` | ''}` | `/MM/main${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MM/searchResult${`?${string}` | `#${string}` | ''}` | `/MM/searchResult${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MM/searchScreen${`?${string}` | `#${string}` | ''}` | `/MM/searchScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu/favorite${`?${string}` | `#${string}` | ''}` | `/menu/favorite${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu/login${`?${string}` | `#${string}` | ''}` | `/menu/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu/settings${`?${string}` | `#${string}` | ''}` | `/menu/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu/terms${`?${string}` | `#${string}` | ''}` | `/menu/terms${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/SubwayMap` | `/MM/SubwayMap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/loading` | `/MM/loading`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/location` | `/MM/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/main` | `/MM/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/searchResult` | `/MM/searchResult`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MM/searchScreen` | `/MM/searchScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/favorite` | `/menu/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/login` | `/menu/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/settings` | `/menu/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu/terms` | `/menu/terms`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
